### ISSUE TITLE
Verify don't ignore order

### ISSUE THREAD

**Issue by mdunisch** [workshopper/learn-sass#32]
This solution for exercise 2 don't pass: 

``` css
aside {

  a {
    color: red;
  }

  ul {
    margin: 0;
  }
}
```

Basically it's the same like your solution and it matches the requirements. Maybe you could improve the verify-function.
